### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by rgluskin** [mflevine/jupyterlab_html#5]
Hi,
I'm trying to install your extension on my aws ubuntu machine.
It seems to get stuck when resolving packages:
```
$ jupyter labextension install @mflevine/jupyterlab_html
> /usr/bin/npm pack @mflevine/jupyterlab_html
npm notice
npm notice 📦  @mflevine/jupyterlab_html@0.1.4
npm notice === Tarball Contents ===
npm notice 1.1kB package.json
npm notice 1.5kB LICENSE
npm notice 770B  README.md
npm notice 963B  lib/index.d.ts
npm notice 3.5kB lib/index.js
npm notice 681B  style/html5-icon.svg
npm notice 1.1kB style/index.css
npm notice === Tarball Details ===
npm notice name:          @mflevine/jupyterlab_html
npm notice version:       0.1.4
npm notice filename:      mflevine-jupyterlab_html-0.1.4.tgz
npm notice package size:  4.2 kB
npm notice unpacked size: 9.7 kB
npm notice shasum:        a71d2f85131efacf94c545d19629bead3dbd7951
npm notice integrity:     sha512-rcH1v4grQ+4Sh[...]zmQM0mXr3FKiw==
npm notice total files:   7
npm notice
mflevine-jupyterlab_html-0.1.4.tgz
> node /mnt/workspace_roman/miniconda3/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.5.1
(node:4014) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info No lockfile found.
[1/4] Resolving packages...
⠠ @mflevine/jupyterlab_html@file:../extensions/mflevine-jupyterlab_html-0.1.4.tgz
⠁ @mflevine/jupyterlab_html@file:../extensions/mflevine-jupyterlab_html-0.1.4.tgz
⢀ @mflevine/jupyterlab_html@file:../extensions/mflevine-jupyterlab_html-0.1.4.tgz
⠂ @mflevine/jupyterlab_html@file:../extensions/mflevine-jupyterlab_html-0.1.4.tgz^CTraceback (most recent call last):
  File "/mnt/workspace_roman/miniconda3/bin/jupyter-labextension", line 11, in <module>
    sys.exit(main())
  File "/mnt/workspace_roman/miniconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/mnt/workspace_roman/miniconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/mnt/workspace_roman/miniconda3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 213, in start
    super(LabExtensionApp, self).start()
  File "/mnt/workspace_roman/miniconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/mnt/workspace_roman/miniconda3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 75, in start
    logger=self.log, command=command)
  File "/mnt/workspace_roman/miniconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 259, in build
    command=command, clean_staging=clean_staging)
  File "/mnt/workspace_roman/miniconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 400, in build
    self._run(['node', YARN_PATH, 'install'], cwd=staging)
  File "/mnt/workspace_roman/miniconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 1278, in _run
    return proc.wait()
  File "/mnt/workspace_roman/miniconda3/lib/python3.6/site-packages/jupyterlab/process.py", line 108, in wait
    time.sleep(1.)
KeyboardInterrupt

```
I also tried cloning the repo and building locally as in your installation instructions but got stuck on the same problem...
any idea what could be wrong ?

Thanks,
Roman

**Comment by mflevine** [comment]
Weird. I don't think this is an issue specific to this package. The KeyboardInterrupt suggests it was killed by something external?

**Comment by rgluskin** [comment]
I killed it after it was stuck for a very long time....

**Comment by mflevine** [comment]
Have you been able to install other packages?

**Comment by rgluskin** [comment]
I tried installing the jupyterlab discovery extension but it got in the build queue after the html extension so it got stuck. I'm not familiar at all with the node/npm so no idea how to handle that.
In any case, I tried repeating the process on a stronger aws machine and it worked there. So maybe t2 small just wasn't strong enough.
